// lib/dummy-data.ts
// This file contains dummy data for development and testing

// Sample users data
export const users = [
  {
    id: 101,
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    password: "password123", // In a real app, this would be hashed
    role: "borrower",
    borrowerProfile: {
      id: 101,
      name: "John Doe",
      email: "john@example.com",
      borrowCount: 3,
      hasOverdue: false,
    },
  },
  {
    id: 102,
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah@example.com",
    password: "password123", // In a real app, this would be hashed
    role: "borrower",
    borrowerProfile: {
      id: 102,
      name: "Sarah Johnson",
      email: "sarah@example.com",
      borrowCount: 1,
      hasOverdue: true,
    },
  },
  {
    id: 103,
    firstName: "Admin",
    lastName: "User",
    email: "admin@example.com",
    password: "admin123", // In a real app, this would be hashed
    role: "librarian",
  },
]

// Sample library items data
export const libraryItems = [
  {
    id: 1,
    title: "The Great Gatsby",
    creator: "F. Scott Fitzgerald",
    type: "book",
    genre: "Fiction",
    year: 1925,
    available: true,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description: "A story of wealth, love, and the American Dream in the 1920s.",
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    creator: "Harper Lee",
    type: "book",
    genre: "Fiction",
    year: 1960,
    available: true,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description: "A powerful story of racial injustice and moral growth in the American South.",
  },
  {
    id: 3,
    title: "1984",
    creator: "George Orwell",
    type: "book",
    genre: "Science Fiction",
    year: 1949,
    available: false,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description: "A dystopian novel about totalitarianism, surveillance, and thought control.",
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    creator: "Jane Austen",
    type: "audiobook",
    genre: "Romance",
    year: 2013,
    available: true,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description: "A romantic novel about the Bennet family and the proud Mr. Darcy.",
    narrator: "Rosamund Pike",
    duration: "11h 35m",
  },
  {
    id: 5,
    title: "The Hobbit",
    creator: "J.R.R. Tolkien",
    type: "audiobook",
    genre: "Fantasy",
    year: 2012,
    available: true,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description: "A fantasy novel about Bilbo Baggins and his adventure with dwarves.",
    narrator: "Andy Serkis",
    duration: "10h 25m",
  },
  {
    id: 6,
    title: "Harry Potter and the Sorcerer's Stone",
    creator: "J.K. Rowling",
    type: "audiobook",
    genre: "Fantasy",
    year: 2015,
    available: false,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description: "The first book in the Harry Potter series about a young wizard.",
    narrator: "Jim Dale",
    duration: "8h 33m",
  },
  {
    id: 7,
    title: "The Shawshank Redemption",
    creator: "Frank Darabont",
    type: "dvd",
    genre: "Drama",
    year: 1994,
    available: true,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    runtime: "142 min",
    rating: "R",
  },
  {
    id: 8,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    creator: "Peter Jackson",
    type: "dvd",
    genre: "Fantasy",
    year: 2001,
    available: true,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description:
      "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    runtime: "178 min",
    rating: "PG-13",
  },
  {
    id: 9,
    title: "Inception",
    creator: "Christopher Nolan",
    type: "dvd",
    genre: "Science Fiction",
    year: 2010,
    available: false,
    coverUrl: "/placeholder.svg?height=200&width=150",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    runtime: "148 min",
    rating: "PG-13",
  },
]

// Sample borrow requests data
export const borrowRequests = [
  {
    id: 1,
    borrower: {
      id: 101,
      name: "John Doe",
      email: "john@example.com",
      borrowCount: 3,
      hasOverdue: false,
    },
    item: {
      id: 1,
      title: "The Great Gatsby",
      creator: "F. Scott Fitzgerald",
      type: "book",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    requestDate: "2023-05-14T09:30:00",
    borrowDate: "2023-05-15",
    returnDate: "2023-06-05",
    status: "pending",
    notes: "First time reading this classic",
  },
  {
    id: 2,
    borrower: {
      id: 102,
      name: "Sarah Johnson",
      email: "sarah@example.com",
      borrowCount: 1,
      hasOverdue: true,
    },
    item: {
      id: 4,
      title: "Pride and Prejudice",
      creator: "Jane Austen",
      type: "audiobook",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    requestDate: "2023-05-14T10:15:00",
    borrowDate: "2023-05-16",
    returnDate: "2023-05-30",
    status: "pending",
    notes: "",
  },
  {
    id: 3,
    borrower: {
      id: 103,
      name: "Michael Brown",
      email: "michael@example.com",
      borrowCount: 2,
      hasOverdue: false,
    },
    item: {
      id: 7,
      title: "The Shawshank Redemption",
      creator: "Frank Darabont",
      type: "dvd",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    requestDate: "2023-05-14T11:45:00",
    borrowDate: "2023-05-15",
    returnDate: "2023-05-22",
    status: "pending",
    notes: "Looking forward to watching this classic film",
  },
  {
    id: 4,
    borrower: {
      id: 104,
      name: "Emma Wilson",
      email: "emma@example.com",
      borrowCount: 0,
      hasOverdue: false,
    },
    item: {
      id: 2,
      title: "To Kill a Mockingbird",
      creator: "Harper Lee",
      type: "book",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    requestDate: "2023-05-13T14:20:00",
    borrowDate: "2023-05-15",
    returnDate: "2023-06-05",
    status: "pending",
    notes: "For school assignment",
  },
  {
    id: 5,
    borrower: {
      id: 102,
      name: "Sarah Johnson",
      email: "sarah@example.com",
      borrowCount: 1,
      hasOverdue: true,
    },
    item: {
      id: 3,
      title: "1984",
      creator: "George Orwell",
      type: "book",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    requestDate: "2023-05-13T16:05:00",
    borrowDate: "2023-05-15",
    returnDate: "2023-06-05",
    status: "pending",
    notes: "",
  },
]

// Sample borrowed items data
export const borrowedItems = [
  {
    id: 1,
    item: {
      id: 1,
      title: "The Great Gatsby",
      creator: "F. Scott Fitzgerald",
      type: "book",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    borrower: {
      id: 101,
      name: "John Doe",
      email: "john@example.com",
    },
    borrowDate: "2023-05-01",
    dueDate: "2023-05-22",
    status: "borrowed",
    isOverdue: false,
  },
  {
    id: 2,
    item: {
      id: 4,
      title: "Pride and Prejudice",
      creator: "Jane Austen",
      type: "audiobook",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    borrower: {
      id: 101,
      name: "John Doe",
      email: "john@example.com",
    },
    borrowDate: "2023-05-05",
    dueDate: "2023-05-19",
    status: "borrowed",
    isOverdue: false,
  },
  {
    id: 3,
    item: {
      id: 7,
      title: "The Shawshank Redemption",
      creator: "Frank Darabont",
      type: "dvd",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    borrower: {
      id: 101,
      name: "John Doe",
      email: "john@example.com",
    },
    borrowDate: "2023-04-25",
    dueDate: "2023-05-02",
    status: "borrowed",
    isOverdue: true,
  },
]

// Sample fines data
export const fines = [
  {
    id: 1,
    borrower: {
      id: 101,
      name: "John Doe",
      email: "john@example.com",
      borrowCount: 3,
      hasOverdue: false,
    },
    item: {
      id: 1,
      title: "The Great Gatsby",
      creator: "F. Scott Fitzgerald",
      type: "book",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    dueDate: "2023-04-15",
    returnDate: "2023-04-25",
    daysLate: 10,
    amount: 2.5,
    status: "unpaid",
  },
  {
    id: 2,
    borrower: {
      id: 102,
      name: "Sarah Johnson",
      email: "sarah@example.com",
      borrowCount: 1,
      hasOverdue: true,
    },
    item: {
      id: 7,
      title: "The Shawshank Redemption",
      creator: "Frank Darabont",
      type: "dvd",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    dueDate: "2023-05-01",
    returnDate: "2023-05-08",
    daysLate: 7,
    amount: 3.5,
    status: "unpaid",
  },
  {
    id: 3,
    borrower: {
      id: 103,
      name: "Michael Brown",
      email: "michael@example.com",
      borrowCount: 2,
      hasOverdue: false,
    },
    item: {
      id: 3,
      title: "1984",
      creator: "George Orwell",
      type: "book",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    dueDate: "2023-03-10",
    returnDate: "2023-03-15",
    daysLate: 5,
    amount: 1.25,
    status: "paid",
    paidDate: "2023-03-16",
    paymentMethod: "Credit Card",
    transactionId: "TXN123456",
  },
  {
    id: 4,
    borrower: {
      id: 104,
      name: "Emma Wilson",
      email: "emma@example.com",
      borrowCount: 0,
      hasOverdue: false,
    },
    item: {
      id: 2,
      title: "To Kill a Mockingbird",
      creator: "Harper Lee",
      type: "book",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    dueDate: "2023-05-20",
    returnDate: null,
    daysLate: 0,
    amount: 0,
    status: "current",
  },
  {
    id: 5,
    borrower: {
      id: 102,
      name: "Sarah Johnson",
      email: "sarah@example.com",
      borrowCount: 1,
      hasOverdue: true,
    },
    item: {
      id: 5,
      title: "The Hobbit",
      creator: "J.R.R. Tolkien",
      type: "audiobook",
      coverUrl: "/placeholder.svg?height=60&width=40",
    },
    dueDate: "2023-04-30",
    returnDate: null,
    daysLate: 8,
    amount: 2.0,
    status: "overdue",
  },
]

// Sample payment history data
export const paymentHistory = [
  {
    id: "PMT001",
    date: "2023-05-16T14:32:00",
    borrower: {
      id: 101,
      name: "John Doe",
      email: "john@example.com",
    },
    items: [{ id: 3, title: "1984", creator: "George Orwell", type: "book" }],
    amount: 1.25,
    method: "Credit Card",
    cardLast4: "4242",
    status: "completed",
    transactionId: "TXN123456",
    processedBy: "System (Online)",
  },
  {
    id: "PMT002",
    date: "2023-05-15T11:20:00",
    borrower: {
      id: 102,
      name: "Sarah Johnson",
      email: "sarah@example.com",
    },
    items: [{ id: 7, title: "The Shawshank Redemption", creator: "Frank Darabont", type: "dvd" }],
    amount: 3.5,
    method: "Cash",
    status: "completed",
    transactionId: "TXN123457",
    processedBy: "Admin (Jane Smith)",
  },
  {
    id: "PMT003",
    date: "2023-05-14T09:45:00",
    borrower: {
      id: 103,
      name: "Michael Brown",
      email: "michael@example.com",
    },
    items: [
      { id: 1, title: "The Great Gatsby", creator: "F. Scott Fitzgerald", type: "book" },
      { id: 4, title: "Pride and Prejudice", creator: "Jane Austen", type: "audiobook" },
    ],
    amount: 5.75,
    method: "Credit Card",
    cardLast4: "1234",
    status: "completed",
    transactionId: "TXN123458",
    processedBy: "System (Online)",
  },
  {
    id: "PMT004",
    date: "2023-05-12T16:15:00",
    borrower: {
      id: 104,
      name: "Emma Wilson",
      email: "emma@example.com",
    },
    items: [{ id: 2, title: "To Kill a Mockingbird", creator: "Harper Lee", type: "book" }],
    amount: 2.0,
    method: "Waived",
    status: "waived",
    transactionId: "TXN123459",
    processedBy: "Admin (Robert Johnson)",
  },
]

// Sample content requests data
export const contentRequests = [
  {
    id: 1,
    userId: 101,
    title: "Dune",
    author: "Frank Herbert",
    category: "Science Fiction",
    isbn: "9780441172719",
    description: "A science fiction novel about a desert planet with valuable resources.",
    reason: "Many patrons have requested this classic sci-fi novel.",
    urgency: "normal",
    requestDate: "2023-05-10T09:15:00",
    status: "pending",
  },
  {
    id: 2,
    userId: 102,
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    isbn: "9780062315007",
    description: "A philosophical novel about a shepherd boy's journey to find treasure.",
    reason: "Personal interest in philosophy and self-discovery.",
    urgency: "low",
    requestDate: "2023-05-08T14:30:00",
    status: "approved",
  },
  {
    id: 3,
    userId: 103,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
    isbn: "9780062316097",
    description: "A book about the history and impact of Homo sapiens.",
    reason: "Educational purposes for a research project.",
    urgency: "high",
    requestDate: "2023-05-12T11:45:00",
    status: "declined",
    declineReason: "Already in our collection, please check catalog section B12.",
  },
]

// Export all dummy data
export const dummyData = {
  users,
  libraryItems,
  borrowRequests,
  borrowedItems,
  fines,
  paymentHistory,
  contentRequests,
}

export default dummyData
